### ISSUE TITLE
A Coach mark with 'hasNext' and no 'currentCM' and 'totalCM' displays undefined/undefined on coachmark

### ISSUE THREAD

**Issue by vshivp2** [Pearson-Higher-Ed/o-coach-mark#18]
When a user creates a coach mark with the attribute 'hasNext' but does NOT define 'currentCM' and 'totalCM' attributes, observe that the coach mark displays undefined/undefined text within the coachmark.

<img width="479" alt="undefined text on coachmark" src="https://cloud.githubusercontent.com/assets/17303073/14923362/05d82c60-0dfa-11e6-87b8-c9734f7e1a6d.png">

**Comment by richweclg** [comment]
Fixed with AEGIS-179
